<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Authors>packet-net</Authors>
    <PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/packet-net/pdn-mailcast</RepositoryUrl>
  </PropertyGroup>
</Project>
