<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Packet.Mailcast\Packet.Mailcast.csproj" />
  </ItemGroup>

</Project>
