<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Mailcast.Core</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mailcast.RaptorQ\Mailcast.RaptorQ.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Dictionaries\*.zdict" LogicalName="Mailcast.Core.Dictionaries.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Mailcast.Core.Tests" />
  </ItemGroup>

</Project>
